### ISSUE TITLE
Offset in Build

### ISSUE THREAD

**Issue by mrblacksoot** [CamilleChiquet/2D-Water-Reflection#1]
Hello CamilleChiquet,
to begin with, I discovered your YoutubeVideo and really like your 2D-Water-Reflection, thank you for sharing!
It works very well in the Scene-View and in Game-Mode, but sadly there is an offset once I make a Build.

Is it a known issue? 
Best regards
MrBlacksoot 

![water_reflection_offset](https://user-images.githubusercontent.com/107774413/188217994-72defc5b-b2b9-42ec-b8e5-1ee1135e02d9.png)

**Comment by CamilleChiquet** [comment]
Hi MrBlacksoot,

I'm glad you liked it !
I have never done any buid with this asset and never heard about this
problem, that's weird...
Can you send me a sample project where the bug is present ? I'll take a
look at in my spare time.

Have a nice day,
Camille

Le ven. 2 sept. 2022 à 20:44, mrblacksoot ***@***.***> a
écrit :

**Comment by mrblacksoot** [comment]
Hello Camille,
I tried to set up a sample project. Hope it worked: https://github.com/mrblacksoot/reflection-bug-showcase

Best regards,
MrBlacksoot

**Comment by CamilleChiquet** [comment]
Ok bug found.

The water texture used by the shader wasn't present in the build.
I suspect the fact that this texture is only used by the shader and not by any asset in the game so maybe it was automatically removed from the build.
Now the water reflection script include a new field to link to the water Texture (By default the existing one, Prefab updated).

Files updated, the problem should be fixed now.

**Comment by CamilleChiquet** [comment]
@mrblacksoot Is the issue solved ?

**Comment by mrblacksoot** [comment]
Hello @CamilleChiquet, I tried the new prefab in the showcase-repo, and it works now. Thanks a lot for the quick fix!
